#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-nanoserver-1803 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-nanoserver-1803 AS build
WORKDIR /src
COPY ["HelloWorld2.1/HelloWorld2.1.csproj", "HelloWorld2.1/"]
RUN dotnet restore "HelloWorld2.1/HelloWorld2.1.csproj"
COPY . .
WORKDIR "/src/HelloWorld2.1"
RUN dotnet build "HelloWorld2.1.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "HelloWorld2.1.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HelloWorld2.1.dll"]